name: anniversary_date_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  firebase_analytics: ^11.3.6
  firebase_core: ^3.9.0
  firebase_messaging: ^15.1.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_local_notifications: ^18.0.1
  flutter_localizations:
    sdk: flutter
  fluttertoast: ^8.2.10
  form_field_validator: ^1.1.0
  get_it: ^8.0.2
  google_fonts: ^6.2.1
  intl: any
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
